### 准备数据集

In [2]:
# 配置代码
import os

os.environ['http_proxy'] = '127.0.0.1:10809'
os.environ['https_proxy'] = '127.0.0.1:10809'

In [3]:
# 加载tokenizer
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('hfl/rbt3')

In [4]:
tokenizer

BertTokenizerFast(name_or_path='hfl/rbt3', vocab_size=21128, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [5]:
# 试用
tokenizer.batch_encode_plus(['明月装饰了你的窗子', '你装饰了别人的梦'], 
                           truncation=True)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'input_ids': [[101, 3209, 3299, 6163, 7652, 749, 872, 4638, 4970, 2094, 102], [101, 872, 6163, 7652, 749, 1166, 782, 4638, 3457, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [6]:
# 从磁盘加载中文数据集
from datasets import load_from_disk

dataset = load_from_disk('./data/ChnSentiCorp/')

In [7]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 9600
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 0
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1200
    })
})

In [8]:
# 缩小数据规模, 便于测试. 
dataset['train'] = dataset['train'].shuffle().select(range(2000))
dataset['test'] = dataset['test'].shuffle().select(range(100))

In [9]:
dataset['train'][0]

{'text': '书的名字绝对讨好人，我相信很多人和我一样，因为书名而买了这本书。书里的内容没有什么新意，是你我小时候爸妈，老师教导的那套。可以当立志的读本。',
 'label': 0}

In [12]:
def f(data, tokenizer):
    return tokenizer.batch_encode_plus(data['text'], truncation=True)

dataset = dataset.map(f, batched=True,
                     batch_size=1000,
                     num_proc=4,
                     remove_columns=['text'],
                     fn_kwargs={'tokenizer': tokenizer})

dataset

Map (num_proc=4):   0%|          | 0/2000 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/100 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    validation: Dataset({
        features: ['label'],
        num_rows: 0
    })
    test: Dataset({
        features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 100
    })
})

In [13]:
# 删掉太长的句子
def f(data):
    return [len(i) <= 512 for i in data['input_ids']]

dataset = dataset.filter(f, batched=True, batch_size=1000, num_proc=4)

Filter (num_proc=4):   0%|          | 0/2000 [00:00<?, ? examples/s]

Filter (num_proc=4):   0%|          | 0/100 [00:00<?, ? examples/s]

In [14]:
from transformers import AutoModelForSequenceClassification

In [15]:
model = AutoModelForSequenceClassification.from_pretrained('hfl/rbt3', num_labels=2)

Some weights of the model checkpoint at hfl/rbt3 were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at hfl/rbt3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [16]:
# 统计模型参数量
sum([i.nelement() for i in model.parameters()])

38478338

In [18]:
# 模型试算
import torch

# 模拟一条数据
data = {
    'input_ids': torch.ones(4, 10, dtype=torch.long),
    'token_type_ids': torch.ones(4, 10, dtype=torch.long),
    'attention_mask': torch.ones(4, 10, dtype=torch.long),
    'labels': torch.ones(4, dtype=torch.long)
}

out = model(**data)

In [19]:
out

SequenceClassifierOutput(loss=tensor(0.8028, grad_fn=<NllLossBackward0>), logits=tensor([[0.2630, 0.0546],
        [0.2630, 0.0546],
        [0.2630, 0.0546],
        [0.2630, 0.0546]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [20]:
out['loss']

tensor(0.8028, grad_fn=<NllLossBackward0>)

In [23]:
out['logits']

tensor([[0.2630, 0.0546],
        [0.2630, 0.0546],
        [0.2630, 0.0546],
        [0.2630, 0.0546]], grad_fn=<AddmmBackward0>)

In [24]:
# 定义评价函数
from datasets import load_metric

metric = load_metric('accuracy')

D:\.venv\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  after removing the cwd from sys.path.

In [34]:
import numpy as np
from transformers.trainer_utils import EvalPrediction

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    pred = logits.argmax(axis=1)
    # 不用metric, 自己算也行
    return {'accuracy': (pred == labels).mean()}
#     print(pred)
#     print(labels)
#     return metric.compute(predctions=pred, references=labels)


# 模拟输出

eval_pred = EvalPrediction(
    predictions=np.array([[0, 1], [2, 3], [4, 5], [6, 7]]),
    label_ids=np.array([1, 1, 0, 1])
)
compute_metrics(eval_pred)

{'accuracy': 0.75}

In [33]:
# 这个版本的准确率有bug. 暂时不用. 
predictions=np.array([0, 0, 1, 0])
references = np.array([1, 0, 1, 0])
metric.compute(predctions=predictions, references=references)

TypeError: 'NoneType' object is not iterable

In [35]:
# 定义训练参数
from transformers import TrainingArguments

In [37]:
args = TrainingArguments(
    # 定义临时数据保存路径
    output_dir = './output_dir',
    
    # 定义测试执行策略, 可取 no, epoch, steps
    evaluation_strategy = 'steps', 
    
    # 定义每隔多少个step执行一次测试
    eval_steps = 30,
    
    # 定义模型保存策略, 可取 no, epoch, steps
    save_strategy = 'steps',
    
    # 定义每隔多少个step保存一次
    save_steps = 30,
    
    # 定义总共训练集个轮次
    num_train_epochs = 1,
    
    # 定义学习率
    learning_rate = 1e-4,
    
    # 加入参数权重衰减, 防止过拟合
    weight_decay = 1e-2,
    
    # 定义训练和测试时候的批次大小
    per_device_eval_batch_size = 16,
    per_device_train_batch_size = 16,
    
    # 定义是否使用GPU训练
    no_cuda = False
)

In [38]:
# 定义训练器
from transformers import Trainer
from transformers.data.data_collator import DataCollatorWithPadding

In [40]:
trainer = Trainer(
    model = model,
    args = args,
    train_dataset = dataset['train'],
    eval_dataset = dataset['test'],
    compute_metrics = compute_metrics,
    data_collator = DataCollatorWithPadding(tokenizer)
)

In [41]:
# 测试数据整理函数
data_collator = DataCollatorWithPadding(tokenizer)

In [43]:
# 获取一批数据
data = dataset['train'][:5]
print(data)

{'label': [0, 0, 1, 0, 1], 'input_ids': [[101, 741, 4638, 1399, 2099, 5318, 2190, 6374, 1962, 782, 8024, 2769, 4685, 928, 2523, 1914, 782, 1469, 2769, 671, 3416, 8024, 1728, 711, 741, 1399, 5445, 743, 749, 6821, 3315, 741, 511, 741, 7027, 4638, 1079, 2159, 3766, 3300, 784, 720, 3173, 2692, 8024, 3221, 872, 2769, 2207, 3198, 952, 4268, 1968, 8024, 5439, 2360, 3136, 2193, 4638, 6929, 1947, 511, 1377, 809, 2496, 4989, 2562, 4638, 6438, 3315, 511, 102], [101, 3141, 4178, 6206, 1962, 754, 10972, 6821, 763, 3322, 1690, 8024, 6134, 7481, 2523, 1117, 511, 852, 3221, 6858, 6814, 12311, 9683, 8165, 3466, 3844, 8476, 3946, 2428, 671, 5663, 1762, 8347, 118, 8419, 722, 7313, 8024, 4801, 4669, 1469, 712, 3352, 4638, 3946, 2428, 6772, 3633, 2382, 8024, 852, 3221, 8476, 2218, 2607, 2587, 749, 511, 2828, 9201, 1305, 3123, 1762, 6438, 1305, 1690, 7027, 7481, 2233, 4197, 1357, 679, 1139, 3341, 749, 8024, 3209, 1921, 6206, 2145, 3302, 3018, 2137, 511, 102], [101, 5050, 3221, 3867, 6897, 6438, 4289, 704, 6820, 6121, 4638, 741, 2828, 511, 1963, 3362, 6432, 3221, 837, 6381, 8024, 948, 738, 6121, 8024, 852, 3221, 1963, 3634, 671, 3341, 8024, 6821, 702, 837, 6381, 4293, 2816, 4638, 782, 4289, 3313, 1048, 6814, 1914, 8024, 5050, 3221, 5882, 792, 4767, 4638, 837, 6381, 8024, 6820, 3221, 2096, 753, 2207, 1995, 4638, 1450, 8043, 2496, 4197, 6821, 3221, 2458, 4381, 5010, 511, 741, 3221, 1962, 741, 8024, 2190, 1325, 1380, 738, 679, 6814, 1914, 6397, 817, 8024, 2682, 2553, 1091, 6421, 741, 4638, 782, 3221, 1066, 772, 1054, 1447, 2828, 8043, 2792, 809, 2533, 3300, 2792, 7560, 2555, 511, 1521, 8024, 2190, 749, 8024, 6438, 6821, 3315, 741, 8024, 872, 1166, 2682, 6496, 2768, 3221, 1225, 2562, 4638, 6929, 4905, 8024, 1333, 1728, 677, 7481, 671, 1368, 738, 6432, 749, 511, 6821, 123, 3315, 741, 1217, 671, 6629, 8024, 1331, 2428, 4685, 2496, 1377, 6225, 1521, 8024, 5445, 684, 3221, 1920, 2458, 3315, 6929, 4905, 511, 102], [101, 2769, 2582, 720, 2823, 679, 1168, 4954, 855, 8024, 2600, 6230, 2533, 741, 704, 3300, 4157, 1430, 4281, 8024, 2215, 1071, 3221, 1184, 6241, 3030, 1139, 2360, 4862, 2360, 4266, 4638, 1405, 1544, 782, 8024, 1008, 3636, 3360, 7770, 782, 849, 4638, 102], [101, 691, 6205, 2523, 679, 7231, 8024, 2595, 5543, 1469, 1912, 6225, 6963, 2523, 1377, 6225, 511, 7478, 2382, 679, 7231, 8024, 1372, 3221, 6163, 5143, 5320, 3198, 833, 5905, 2242, 8024, 1400, 3341, 1762, 5468, 2682, 5381, 4991, 2798, 2823, 1168, 749, 6237, 1104, 1215, 3791, 8024, 2533, 2828, 4801, 4669, 4638, 671, 702, 691, 6205, 5314, 1068, 2957, 2798, 6121, 8024, 679, 6381, 2533, 1373, 784, 720, 749, 8024, 1920, 2157, 1168, 5381, 677, 1343, 4692, 2218, 1962, 749, 511, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [44]:
# 查看句子长度
for i in data['input_ids']:
    print(len(i))

72
85
167
44
83

In [45]:
# 调用数据整理函数, 进行整理
data = data_collator(data)

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

In [46]:
# 查看整理之后的数据
for k, v in data.items():
    print(k, v.shape)

input_ids torch.Size([5, 167])
token_type_ids torch.Size([5, 167])
attention_mask torch.Size([5, 167])
labels torch.Size([5])

In [47]:
data

{'input_ids': tensor([[  101,   741,  4638,  1399,  2099,  5318,  2190,  6374,  1962,   782,
          8024,  2769,  4685,   928,  2523,  1914,   782,  1469,  2769,   671,
          3416,  8024,  1728,   711,   741,  1399,  5445,   743,   749,  6821,
          3315,   741,   511,   741,  7027,  4638,  1079,  2159,  3766,  3300,
           784,   720,  3173,  2692,  8024,  3221,   872,  2769,  2207,  3198,
           952,  4268,  1968,  8024,  5439,  2360,  3136,  2193,  4638,  6929,
          1947,   511,  1377,   809,  2496,  4989,  2562,  4638,  6438,  3315,
           511,   102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [  101,  3141,  4178,  6206,  1962,   754, 10972,  6821,   763,  3322,
          1690,  8024,  6134,  7481,  2523,  1117,   511,   852,  3221,  6858,
          6814, 12311,  9683,  8165,  3466,  3844,  8476,  3946,  2428,   671,
          5663,  1762,  8347,   118,  8419,   722,  7313,  8024,  4801,  4669,
          1469,   712,  3352,  4638,  3946,  2428,  6772,  3633,  2382,  8024,
           852,  3221,  8476,  2218,  2607,  2587,   749,   511,  2828,  9201,
          1305,  3123,  1762,  6438,  1305,  1690,  7027,  7481,  2233,  4197,
          1357,   679,  1139,  3341,   749,  8024,  3209,  1921,  6206,  2145,
          3302,  3018,  2137,   511,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [  101,  5050,  3221,  3867,  6897,  6438,  4289,   704,  6820,  6121,
          4638,   741,  2828,   511,  1963,  3362,  6432,  3221,   837,  6381,
          8024,   948,   738,  6121,  8024,   852,  3221,  1963,  3634,   671,
          3341,  8024,  6821,   702,   837,  6381,  4293,  2816,  4638,   782,
          4289,  3313,  1048,  6814,  1914,  8024,  5050,  3221,  5882,   792,
          4767,  4638,   837,  6381,  8024,  6820,  3221,  2096,   753,  2207,
          1995,  4638,  1450,  8043,  2496,  4197,  6821,  3221,  2458,  4381,
          5010,   511,   741,  3221,  1962,   741,  8024,  2190,  1325,  1380,
           738,   679,  6814,  1914,  6397,   817,  8024,  2682,  2553,  1091,
          6421,   741,  4638,   782,  3221,  1066,   772,  1054,  1447,  2828,
          8043,  2792,   809,  2533,  3300,  2792,  7560,  2555,   511,  1521,
          8024,  2190,   749,  8024,  6438,  6821,  3315,   741,  8024,   872,
          1166,  2682,  6496,  2768,  3221,  1225,  2562,  4638,  6929,  4905,
          8024,  1333,  1728,   677,  7481,   671,  1368,   738,  6432,   749,
           511,  6821,   123,  3315,   741,  1217,   671,  6629,  8024,  1331,
          2428,  4685,  2496,  1377,  6225,  1521,  8024,  5445,   684,  3221,
          1920,  2458,  3315,  6929,  4905,   511,   102],
        [  101,  2769,  2582,   720,  2823,   679,  1168,  4954,   855,  8024,
          2600,  6230,  2533,   741,   704,  3300,  4157,  1430,  4281,  8024,
          2215,  1071,  3221,  1184,  6241,  3030,  1139,  2360,  4862,  2360,
          4266,  4638,  1405,  1544,   782,  8024,  1008,  3636,  3360,  7770,
           782,   849,  4638,   102,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [  101,   691,  6205,  2523,   679,  7231,  8024,  2595,  5543,  1469,
          1912,  6225,  6963,  2523,  1377,  6225,   511,  7478,  2382,   679,
          7231,  8024,  1372,  3221,  6163,  5143,  5320,  3198,   833,  5905,
          2242,  8024,  1400,  3341,  1762,  5468,  2682,  5381,  4991,  2798,
          2823,  1168,   749,  6237,  1104,  1215,  3791,  8024,  2533,  2828,
          4801,  4669,  4638,   671,   702,   691,  6205,  5314,  1068,  2957,
          2798,  6121,  8024,   679,  6381,  2533,  1373,   784,   720,   749,
          8024,  1920,  2157,  1168,  5381,   677,  1343,  4692,  2218,  1962,
           749,   511,   102,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'labels': tensor([0, 0, 1, 0, 1])}

In [48]:
tokenizer.decode(data['input_ids'][0])

'[CLS] 书 的 名 字 绝 对 讨 好 人 ， 我 相 信 很 多 人 和 我 一 样 ， 因 为 书 名 而 买 了 这 本 书 。 书 里 的 内 容 没 有 什 么 新 意 ， 是 你 我 小 时 候 爸 妈 ， 老 师 教 导 的 那 套 。 可 以 当 立 志 的 读 本 。 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [49]:
# 训练和测试

# 测试一把
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 98
  Batch size = 16

{'eval_loss': 0.746782660484314,
 'eval_accuracy': 0.40816326530612246,
 'eval_runtime': 3.0309,
 'eval_samples_per_second': 32.334,
 'eval_steps_per_second': 2.31}

In [50]:
# 训练
trainer.train()

D:\.venv\lib\site-packages\transformers\optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 1978
  Num Epochs = 1
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 124
  Number of trainable parameters = 38478338

***** Running Evaluation *****
  Num examples = 98
  Batch size = 16
Saving model checkpoint to ./output_dir\checkpoint-30
Configuration saved in ./output_dir\checkpoint-30\config.json
Model weights saved in ./output_dir\checkpoint-30\pytorch_model.bin
***** Running Evaluation *****
  Num examples = 98
  Batch size = 16
Saving model checkpoint to ./output_dir\checkpoint-60
Configuration saved in ./output_dir\checkpoint-60\config.json
Model weights saved in ./output_dir\checkpoint-60\pytorch_model.bin
***** Running Evaluation *****
  Num examples = 98
  Batch size = 16
Saving model checkpoint to ./output_dir\checkpoint-90
Configuration saved in ./output_dir\checkpoint-90\config.json
Model weights saved in ./output_dir\checkpoint-90\pytorch_model.bin
***** Running Evaluation *****
  Num examples = 98
  Batch size = 16
Saving model checkpoint to ./output_dir\checkpoint-120
Configuration saved in ./output_dir\checkpoint-120\config.json
Model weights saved in ./output_dir\checkpoint-120\pytorch_model.bin


Training completed. Do not forget to share your model on huggingface.co/models =)

TrainOutput(global_step=124, training_loss=0.40998326578447897, metrics={'train_runtime': 32.7148, 'train_samples_per_second': 60.462, 'train_steps_per_second': 3.79, 'total_flos': 71826088671480.0, 'train_loss': 0.40998326578447897, 'epoch': 1.0})

In [51]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 98
  Batch size = 16

{'eval_loss': 0.2862688899040222,
 'eval_accuracy': 0.8571428571428571,
 'eval_runtime': 0.4737,
 'eval_samples_per_second': 206.868,
 'eval_steps_per_second': 14.776,
 'epoch': 1.0}

In [52]:
# 保存和加载模型
import torch

In [53]:
trainer.save_model(output_dir='./output_dir/save_model')

Saving model checkpoint to ./output_dir/save_model
Configuration saved in ./output_dir/save_model\config.json
Model weights saved in ./output_dir/save_model\pytorch_model.bin

In [54]:
# 加载模型

model.load_state_dict(torch.load('./output_dir/save_model/pytorch_model.bin'))

In [55]:
# 恢复中断训练
trainer.train(resume_from_checkpoint='./output_dir/checkpoint-90')

Loading model from ./output_dir/checkpoint-90.
***** Running training *****
  Num examples = 1978
  Num Epochs = 1
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 124
  Number of trainable parameters = 38478338
  Continuing training from checkpoint, will skip to saved global_step
  Continuing training from epoch 0
  Continuing training from global step 90
  Will skip the first 0 epochs then the first 90 batches in the first epoch. If this takes a lot of time, you can add the `--ignore_data_skip` flag to your launch command, but you will resume the training on data already seen by your model.

  0%|          | 0/90 [00:00<?, ?it/s]

***** Running Evaluation *****
  Num examples = 98
  Batch size = 16
Saving model checkpoint to ./output_dir\checkpoint-120
Configuration saved in ./output_dir\checkpoint-120\config.json
Model weights saved in ./output_dir\checkpoint-120\pytorch_model.bin


Training completed. Do not forget to share your model on huggingface.co/models =)

TrainOutput(global_step=124, training_loss=0.06748032569885254, metrics={'train_runtime': 8.8334, 'train_samples_per_second': 223.923, 'train_steps_per_second': 14.038, 'total_flos': 69834802852152.0, 'train_loss': 0.06748032569885254, 'epoch': 1.0})

In [56]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 98
  Batch size = 16

{'eval_loss': 0.2799054682254791,
 'eval_accuracy': 0.8571428571428571,
 'eval_runtime': 0.5186,
 'eval_samples_per_second': 188.966,
 'eval_steps_per_second': 13.498,
 'epoch': 1.0}

In [57]:
# 预测
model.eval()

# 取一批数据做预测
for i, data in enumerate(trainer.get_eval_dataloader()):
    break
    
for k, v in data.items():
    # 因为model在gpu上训练的, 所以数据也要拷贝到gpu上
    data[k] = v.to('cuda')
    
# 预测
out = model(**data)
pred = out['logits'].argmax(dim=1)

In [58]:
pred

tensor([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0], device='cuda:0')

In [61]:
for i in range(16):
    print(tokenizer.decode(data['input_ids'][i], skip_special_tokens=True))
    print('label=', data['labels'][i].item())
    print('predict=', pred[i].item())

这 本 书 中 的 图 片 很 让 人 触 动 ， 比 如 为 劳 拉 祈 祷 的 校 友 ， 惠 特 尼 和 马 特 的 笑 容 ， 很 动 人 。
label= 1
predict= 1
看 了 这 本 书 ， 很 有 感 触 ， 再 次 从 书 中 看 到 一 个 个 或 让 人 快 乐 、 或 让 人 感 动 、 或 让 人 感 慨 万 千 、 无 奈 长 叹 的 故 事 。 很 多 时 候 ， 成 人 总 是 以 为 自 己 的 迫 切 愿 望 也 是 孩 子 的 需 要 ， 我 们 总 是 将 自 己 的 观 点 、 自 己 的 好 恶 强 加 给 孩 子 ， 我 们 忘 了 ， 在 孩 子 的 眼 中 ， 这 个 世 界 与 成 人 并 不 一 样 。 我 想 ， 阅 读 这 本 书 ， 更 多 的 是 改 变 或 形 成 一 个 观 念 。 要 贴 近 孩 子 ， 要 了 解 孩 子 ， 做 孩 子 的 知 心 人 ， 好 朋 友 ， 用 与 孩 子 一 样 的 眼 睛 与 心 灵 来 体 验 与 观 察 这 个 世 界 。
label= 1
predict= 1
外 观 ， 配 置 ， 价 格 ， 三 个 组 合 起 来 看 是 绝 对 超 值 的 东 东 我 4699 入 手 ， 抢 到 了
label= 1
predict= 1
新 机 拿 到 手 就 有 硬 件 问 题 ， 而 且 等 了 6 天 才 到 货 ， 第 二 天 就 返 修 ， 到 现 在 还 没 得 到 处 理 意 见 ！
label= 0
predict= 0
机 器 的 发 热 量 小 ， 比 意 想 中 的 小 很 多 。 噪 音 控 制 的 很 好 ， 运 行 的 时 候 基 本 听 不 到 什 么 声 音 。 双 核 的 速 度 不 错 。 官 网 上 的 xp 驱 动 也 比 较 好 装 。
label= 1
predict= 1
初 五 住 的 ， 这 么 冷 的 天 没 有 暖 气 ， 没 有 热 水 。 携 程 预 定 前 台 说 没 有 收 到 。 总 之 感 觉 很 业 余 。
label= 0
predict= 0
怀 着 十 分 激 动 的 心 情 放 映 ， 可 是 看 着 看 着 发 现 ， 在 放 映 完 毕 后 ， 出 现 一 集 米 老 鼠 的 动 画 片 ！ 开 始 还 怀 疑 是 不 是 赠 送 的 个 别 现 象 ， 可 是 后 来 发 现 每 张 dvd 后 面 都 有 ！ 真 不 知 道 生 产 商 怎 么 想 的 ， 我 想 看 的 是 猫 和 老 鼠 ， 不 是 米 老 鼠 ！ 如 果 厂 家 是 想 赠 送 的 话 ， 那 就 全 套 米 老 鼠 和 唐 老 鸭 都 赠 送 ， 只 在 每 张 dvd 后 面 添 加 一 集 算 什 么 ？ ？ 简 直 是 画 蛇 添 足 ！ ！
label= 0
predict= 0
有 人 说 ， 21 世 纪 是 东 方 的 世 纪 ， 而 东 方 得 看 中 国 的 崛 起 ， 我 想 ： 是 的 ， 21 世 纪 是 中 华 民 族 复 兴 崛 起 的 世 纪 ！ 但 是 这 种 崛 起 的 前 提 是 我 们 必 须 清 楚 认 识 自 己 ， 看 到 自 己 的 不 足 ， 也 要 看 到 自 己 的 优 势 ， 即 是 中 国 的 影 响 力 ， 对 世 界 的 影 响 力 。 我 想 这 本 书 很 好 的 从 某 一 角 度 为 我 们 指 出 了 这 些 我 们 想 要 了 解 的 东 西 ！
label= 1
predict= 1
win7 全 兼 容 ， 只 需 手 动 安 装 acpi 驱 动 。 ubuntu9. 04 全 兼 容 ， 建 议 装 eeebuntu3. 0 ， 可 支 持 软 开 关 蓝 牙 无 线 摄 像 头 。
label= 1
predict= 1
最 早 接 触 寂 地 画 是 在 《 新 蕾 》 上 ， 后 来 满 心 欢 喜 的 买 了 她 的 第 一 本 画 集 《 我 的 路 1 》 很 喜 欢 那 种 温 暖 的 画 风 ， 也 很 喜 欢 配 画 的 文 字 ， 很 细 腻 ， 有 哲 理 ， 让 人 感 觉 温 馨 。 后 来 她 出 的 每 一 期 都 买 了 回 来 ， 用 四 叶 草 的 包 书 纸 包 好 ， 这 次 这 一 套 买 了 是 给 朋 友 的 ， 。 朋 友 看 到 我 有 一 套 《 我 的 路 》 也 很 想 要 ， 所 以 让 我 帮 她 买 。 开 始 会 担 心 里 面 的 附 赠 品 不 知 道 会 不 会 有 ， 看 来 是 有 的 ， 朋 友 收 到 了 很 开 心 也 很 喜 欢
label= 1
predict= 1
《 瓦 地 的 小 号 》 很 像 影 像 叙 事 ， 非 常 有 画 面 感 ， 举 动 言 语 细 腻 的 像 显 微 镜 下 的 毛 孔 ， 搏 动 着 生 动 的 呼 吸 。 种 族 矛 盾 、 社 会 混 沌 下 的 平 民 爱 情 看 似 云 淡 风 轻 ， 却 最 能 催 生 酸 楚 的 情 绪 ， 就 像 《 平 民 百 万 富 翁 》 的 故 事 最 飘 渺 的 爱 情 云 朵 下 正 是 焦 灼 的 大 地 ， 和 这 片 土 地 上 的 生 活 ， 美 丽 而 残 酷 。 借 用 《 瓦 地 的 小 号 》 中 烙 印 在 人 脑 海 中 的 一 句 话 ： 傻 的 不 是 你 ， 而 是 这 局 势 一 丝 无 奈 ， 几 许 深 刻 。
label= 1
predict= 1
突 然 发 现 大 家 都 手 捧 一 本 《 明 朝 那 些 事 》 才 察 觉 原 来 都 出 到 4 了 ， 赶 紧 从 当 当 上 买 了 一 本 饱 读 。 感 觉 一 般 ， 看 到 一 半 就 进 行 不 下 去 了 。
label= 0
predict= 0
外 观 继 承 了 ibm 的 风 格 配 置 也 不 低 4000 下 的 最 好 选 择 了 屏 幕 够 大 看 电 影 也 足 够
label= 1
predict= 1
酒 店 比 较 陈 旧, 房 间 也 不 大, 有 股 味 道. 早 餐 一 般. 房 价 也 不 便 宜! 总 之 很 一 般.
label= 0
predict= 0
酒 店 的 位 置 不 错 ， 附 近 都 靠 近 购 物 中 心 和 写 字 楼 区 。 以 前 来 大 连 一 直 都 住 ， 但 感 觉 比 较 陈 旧 了 。 住 的 期 间 ， 酒 店 在 进 行 装 修 ， 翻 新 和 升 级 房 间 设 备 。 好 是 好 ， 希 望 到 时 房 价 别 涨 太 多 了 。
label= 1
predict= 1
价 格 要 是 能 再 低 点 就 更 好 了 ！ 京 东 应 该 多 搞 特 价 活 动! 快 递 的 服 务 态 度 不 是 很 好
label= 0
predict= 0